language: java
jdk:
  - openjdk8
addons:
  firefox: "latest"
env:
  global:
    - MOZ_HEADLESS=1
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
script: mvn test
